export const posts = [
  {
    id: 1,
    title:
      'this is the first posts ajiejlkasjf fjaiejfakjdfiaejfak  aiefjadkfjaifj fa eifjajflajfie fjaiejfakejf f iejfajf jfkajfk fajkdjfiejf jfieajfdk iafeje',
    desc: 'this is the description jfiejakdf jfiefja fldjfiejfa jfiaejfklsdj ifejaskdjf iejafdjfie ifeafjeijf fjiaefjak fijaiejfajf fiejafje fiajeijf',
    date: '23-10-2023',
    img: 'assets/1.jpg',
    author: 'james',
  },
  {
    id: 2,
    title: 'this is the second posts',
    desc: 'this is the second description',
    date: '23-10-2023',
    img: 'assets/2.jpg',
    author: 'mac',
  },
  {
    id: 3,
    title: 'this is the third posts',
    desc: 'this is the third description',
    date: '23-10-2023',
    img: 'assets/3.jpg',
    author: 'max',
  },
  {
    id: 4,
    title: 'this is the fourth posts',
    desc: 'this is the fourth description',
    date: '23-10-2023',
    img: 'assets/4.jpg',
    author: 'mav',
  },
  {
    id: 5,
    title: 'this is the fifth posts',
    desc: 'this is the fifth description',
    date: '23-10-2023',
    img: 'assets/5.jpg',
    author: 'az',
  },
  {
    id: 6,
    title: 'this is the sixth posts',
    desc: 'this is the sixth description',
    date: '23-10-2023',
    img: 'assets/6.jpg',
    author: 'zor',
  },
  {
    id: 7,
    title: 'this is the seventh posts',
    desc: 'this is the seventh description',
    date: '23-10-2023',
    img: 'assets/7.jpg',
    author: 'zak',
  },
  {
    id: 8,
    title: 'this is the eighth posts',
    desc: 'this is the eighth description',
    date: '23-10-2023',
    img: 'assets/8.jpg',
    author: 'kb',
  },
  {
    id: 9,
    title: 'this is the ninth posts',
    desc: 'this is the ninth description',
    date: '23-10-2023',
    img: 'assets/9.jpg',
    author: 'kir',
  },
  {
    id: 10,
    title: 'this is the tenth posts',
    desc: 'this is the tenth description',
    date: '23-10-2023',
    img: 'assets/10.jpg',
    author: 'apa',
  },
];
